name: "context learning"
on: push
jobs:
    info-job:
        runs-on: ubuntu-latest
        steps:
            - name: print trigger event
              run: echo "Trigger event is ${{ github.event_name }}"